baseURL = "https://junyubian.github.io/"
languageCode = "en-us"
title = "Junyu Bian"
theme = "hugo-digital-garden-theme"
# themesdir = "../../"
copyright = "Junyu Bian©"

[params]
  name = "Junyu Bian"
  description = "Hi there, welcome!"
  initials = "JB"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/junyu_bian"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/junyubian"
    icon = "fab fa-github"

  [[params.social]]
    name = "Facebook" 
    link = "https://www.facebook.com/profile.php?id=100010301021817"
    icon = "fab fa-facebook"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'