baseURL = 'https://junyubian.github.io/'
languageCode = 'en-us'
title = 'Junyu Bian'
theme = 'smol'

# Parameters
[params]
    subtitle = "\"Salvation lies within.\""
    dateFmt = "01/02/2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/junyubian"
        weight = 1 

    [[menu.footer]]
        name = "Twitter(X)"
        url = "https://twitter.com/junyu_bian"
        weight = 2 

    [[menu.footer]]
        name = "Facebook"
        url = "https://www.facebook.com/profile.php?id=100010301021817"
        weight = 3 

    [[menu.footer]]
        name = "Mail"
        url = "mailto:junyu.bian@qq.com"
        weight = 3 

