site_name: Junyu Bian
site_url: https://junyubian.github.io/
repo_name: junyubian/junyubian.github.io
repo_url: https://github.com/JunyuBian/junyubian.github.io
edit_uri: tree/master/docs
site_description: Junyu Bian
copyright: Copyright &copy; 2022-2024 <a href="https://github.com/JunyuBian" target="_blank" rel="noopener">Junyu Bian</a>

theme: 
  name: 'material'
  language: 'en'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  font: false
  palette:
    - scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JunyuBian/
    # - icon: fontawesome/solid/rss
    #   link: https://blog.tonycrane.cc/
    - icon: fontawesome/solid/house
      link: https://junyubian.github.io/
  analytics:
    provider: custom
    property: G-DYETCPM289

extra_css:
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  # - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  # - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - css/tasklist.css
  - css/custom.css
  - css/card.css
  - css/flink.css
  - css/changelog_extra.css
  # - css/heti.css

extra_javascript:
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js
  # - js/heti.js
  # - js/scheme.js # this is in template 'base.html'

plugins:
  - rss
  - search
  - glightbox:
      width: 80%
  - encryptcontent:  # now just for one page, need to be improved
      title_prefix: "🔒 "
      remember_password: True 
      default_expire_dalay: 48
      decryption_failure_message: 'Try Again'
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - writeups/AAA.md
  - changelog
  - statistics:
      page_check_metadata: comment
  - toc
  - heti
  # - tikzautomata
  # - linkbackward:
  #     wait_time: 0
  #     redirections:
  #       - /ctf/steg/ -> /ctf/misc/steg/
  #       - /ctf/steg/image/ -> /ctf/misc/steg/image/
  #       - /ctf/steg/audio/ -> /ctf/misc/steg/audio/
  #       - /ctf/escapes/ -> /ctf/misc/escapes/
  #       - /ctf/escapes/pysandbox/ -> /ctf/misc/escapes/pysandbox/
  #       - /ctf/forensics/ -> /ctf/misc/forensics/
  #       - /ctf/forensics/mem/ -> /ctf/misc/forensics/mem/
  #       - /ctf/coding/ -> /ctf/misc/coding/
  #       - /ctf/qrcode/ -> /ctf/misc/qrcode/
  #       - /ctf/esolang/ -> /ctf/misc/esolang/
  #       - /cs/pl/c_cpp/ -> /cs/pl/c_cpp/c/
  #       - /hpc/ -> /cs/hpc/hpc101/
  #       - /hpc/hpc101/vectorized/ -> /cs/hpc/hpc101/vectorized/
  #       - /hpc/hpc101/gpu/ -> /cs/hpc/hpc101/gpu/
  #       - /hpc/hpc101/openmp/ -> /cs/hpc/hpc101/openmp/
  #       - /hpc/hpc101/mpi/ -> /cs/hpc/hpc101/mpi/
  #       - /hpc/hpc101/ml/ -> /cs/hpc/hpc101/ml/

not_in_nav: todo.md

nav:
  - Home:
    - index.md
    - ChangeLog: changelog.md
    # - 友链: links.md
  - Computer Science:
    - cs/index.md
    - Algorithms:
      - cs/algorithms/index.md
      - KMP:
        - KMP Algorithm: cs/algorithms/kmp/kmpalgorithm.md
      - others:
        - Diff Array: cs/algorithms/others/diffarray.md
        - Swap Functions: cs/algorithms/others/swapfunctions.md
    - Edge Computing:
      - cs/edgecomputing/index.md
      - fdio:
        - Overview: cs/edgecomputing/fdio/overview.md
        - Fluentbit: cs/edgecomputing/fluentbit/client.md
    - Programming languages:
      - cs/languages/index.md
      - C++:
        - Emplace Back: cs/languages/c++/emplaceback.md
    - Tools:
      - cs/tools/index.md
      - bash:
        - getopts: cs/tools/bash/getopts.md
      - website:
        - hugo: cs/tools/website/hugo.md
  - Leetcode Tracker: 
    - cs/leetcodetracker/index.md
  - Conferences&Papers&Patents:
    - cs/conferences&papers&patents/index.md
