name: ci 
on:
  push:
    branches:
      - master 
      - main
  schedule:
      # Runs everyday at 8:00 AM
      - cron: "0 2 * * *"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${ env.cache_id }
          path: .cache
          restore-keys: |
            mkdocs-material-
      - uses: actions/upload-artifact@v4
        with:
          name: site
      #     path: ./
      # - run: pip install mkdocs-git-revision-date-localized-plugin
      # - run: pip install mkdocs-git-authors-plugin
      # - run: pip install mkdocs-rss-plugin
      # - run: pip install mkdocs-glightbox
      # - run: pip install mkdocs-encryptcontent-plugin
      # - run: pip install mkdocs-git-revision-date-localized-plugin
      # - run: pip install install mkdocs-changelog-plugin
      # - run: pip install mkdocs-statistics-plugin
      # - run: pip install mkdocs-toc-plugin
      # - run: pip install mkdocs-heti-plugin
      # - run: pip install mkdocs-material
      # - run: python -m pip install rich
      # - run: 
      # - run: mkdocs gh-deploy --force
